services:
  tradoc:
    image: ghcr.io/lucas-lepajollec/tradoc:latest
    ports:
      - "2507:2507"
    env_file:
      - path: .env
        required: false
    volumes:
      - ./data:/app/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
