export const AVAILABLE_LANGUAGES = [
  { code: 'en', label: 'Anglais (EN)', labelEn: 'English (EN)', flag: '🇬🇧' },
  { code: 'fr', label: 'Français (FR)', labelEn: 'French (FR)', flag: '🇫🇷' },
  { code: 'es', label: 'Espagnol (ES)', labelEn: 'Spanish (ES)', flag: '🇪🇸' },
  { code: 'de', label: 'Allemand (DE)', labelEn: 'German (DE)', flag: '🇩🇪' },
  { code: 'it', label: 'Italien (IT)', labelEn: 'Italian (IT)', flag: '🇮🇹' },
  { code: 'pt', label: 'Portugais (PT)', labelEn: 'Portuguese (PT)', flag: '🇵🇹' },
  { code: 'ja', label: 'Japonais (JA)', labelEn: 'Japanese (JA)', flag: '🇯🇵' },
  { code: 'zh', label: 'Chinois (ZH)', labelEn: 'Chinese (ZH)', flag: '🇨🇳' },
  { code: 'ko', label: 'Coréen (KO)', labelEn: 'Korean (KO)', flag: '🇰🇷' },
  { code: 'ru', label: 'Russe (RU)', labelEn: 'Russian (RU)', flag: '🇷🇺' },
  { code: 'nl', label: 'Néerlandais (NL)', labelEn: 'Dutch (NL)', flag: '🇳🇱' },
  { code: 'pl', label: 'Polonais (PL)', labelEn: 'Polish (PL)', flag: '🇵🇱' },
  { code: 'auto', label: 'Auto-détection', labelEn: 'Auto-Detect', flag: '🌐' },
];

export const translations = {
  en: {
    // Sidebar & Common Navigation
    nav: {
      appName: 'TraDoc',
      appSubtitle: 'AI Literary Translation',
      projects: 'Dashboard',
      inspector: 'Inspector & Tracking',
      vram: 'Estimator',
      sandbox: 'Test',
      glossaries: 'Glossary',
      settings: 'Settings',
      presets: 'Preset Profiling',
      presetSelect: 'Select Config Preset',
      defaultPreset: 'Default Preset',
      serverStatus: 'LLM Server',
      gpuOnline: 'GPU Online',
      gpuOffline: 'GPU Offline',
      unreachableBanner: 'GPU Server unreachable:',
      checkServerUrl: 'Check server at',
      configureIp: 'Configure IP',
    },

    // Dashboard / Main Upload View
    dashboard: {
      importBook: 'Import a Book',
      dragDropText: 'Drag & drop your file here or click to browse',
      supportedFormats: 'EPUB or PDF file',
      formatBadge: 'EPUB / PDF',
      translationMode: 'EN → FR Translation Mode',
      proofreadMode: 'Proofreading & Editorial Pass Mode',
      proofreadSourcePrompt: 'Select existing project or upload target file for editorial pass:',
      sourceProject: 'Source Project for Editorial Pass',
      uploadNewFile: 'Upload a New File',
      llmModel: 'LLM Model',
      literaryGlossary: 'Literary Glossary',
      noGlossary: 'No glossary',
      startTranslation: 'Start Translation',
      startProofreading: 'Start Editorial Proofreading',
      prepareInspect: 'Prepare & Inspect (Without Running)',
      recentProjects: 'Saved Projects',
      noProjectsYet: 'No active or completed projects found.',
      paused: 'PAUSED',
      completed: 'COMPLETED',
      processing: 'PROCESSING',
      failed: 'FAILED',
      resume: 'Resume',
      pause: 'Pause',
      inspect: 'Inspect',
      downloadEpub: 'EPUB',
      deleteProject: 'Delete Project',
      confirmDelete: 'Permanently delete project "{title}"?',

      // Server Parameters Box
      serverParams: 'Server Parameters',
      provider: 'Provider',
      model: 'Active Model',
      concurrency: 'Concurrency',
      semanticWindow: 'Semantic Window',
      requestsUnit: 'requests',
      tokensUnit: 'tokens',
      editConfig: 'Modify Configuration',

      // Live Tester Widget
      liveTester: 'Live Tester',
      liveTesterDesc: 'Test your sentences and model in 2 seconds without importing a book.',
      openSandbox: 'Open Sandbox',
    },

    // Jobs Inspector & Split Visualizer
    inspector: {
      title: 'Segment Inspector',
      selectProjectPrompt: 'Select a project from the left panel to inspect segments in real time.',
      projectsList: 'Book Projects',
      modeTranslation: 'Translation',
      modeProofread: 'Proofreading',
      segment: 'Segment',
      originalText: 'Original English Text (Source)',
      targetText: 'French Translation Output (Pass 1)',
      proofreadText: 'Editorial Proofread Output (Pass 2)',
      liveSseLogs: 'Live Server-Sent Events (SSE) Stream',
      noLogsYet: 'Waiting for stream logs...',
      copyText: 'Copy',
      copied: 'Copied!',
      reorderNotice: 'Double click on any segment to edit target text directly.',
    },

    // Glossary Manager
    glossary: {
      title: 'Literary Glossaries',
      desc: 'Maintain strict terminology, character names, and universe consistency.',
      aiPromptTitle: '1. AI Prompt Assistant (ChatGPT / Claude)',
      aiPromptDesc: 'Generate a clean glossary from your book using a single AI prompt.',
      copyPromptBtn: 'Copy AI Extraction Prompt',
      promptCopied: 'Prompt copied to clipboard!',

      pasteImportTitle: '2. Import / Paste Glossary Data',
      pasteImportDesc: 'Paste terms generated by your AI (Format: Original | Target | Note) or upload a text file.',
      pastePlaceholder: 'Character_Name | Nom_Français | Note or directive...',
      insertInList: 'Insert into Glossary Below',
      uploadFileBtn: 'Upload Glossary File',

      manualGuideTitle: '3. Manual Creation Guide',
      manualGuideDesc: 'How to build and format your own literary glossary.',
      manualStep1: 'Use 1 line per term with exact spelling.',
      manualStep2: 'Include notes for context (e.g., gender, title, formal vs informal).',

      termsList: 'Glossary Terms Table',
      sourceTerm: 'Source Term (EN)',
      targetTerm: 'Target Translation (FR)',
      noteDirective: 'Note / Editorial Directive',
      action: 'Action',
      addNewTerm: 'Add New Term',
      searchPlaceholder: 'Search glossary terms...',
      noTermsFound: 'No glossary terms defined yet.',
      confirmDeleteTerm: 'Delete term "{term}"?',
      saveGlossary: 'Save Glossary',
      savedSuccess: 'Glossary saved successfully!',
    },

    // Test Sandbox Modal
    sandbox: {
      title: 'Live Sandbox & Prompt Preview',
      desc: 'Test your active LLM model on custom literary excerpts before running large translation jobs.',
      sourceInputLabel: 'Source Excerpt (EN)',
      resultOutputLabel: 'Model Output (FR)',
      sampleText: 'It is a truth universally acknowledged, that a single man in possession of a good fortune, must be in want of a wife.',
      runInference: 'Run Test Inference',
      runningInference: 'Processing inference...',
      resetExcerpt: 'Reset Sample Text',
      copyResult: 'Copy Translation',
    },

    // Setup Wizard / VRAM Cost Estimator
    wizard: {
      title: 'VRAM & Processing Cost Estimator',
      desc: 'Calculate token consumption, GPU VRAM requirements, and API costs.',
      pageCountLabel: 'Number of Book Pages',
      sliderLabel: 'Page count slider',
      pagesUnit: 'pages',
      wordsEstimate: 'Estimated word count: ~{count} words',
      estimatedSegments: 'Estimated Segments ({chunkSize} tokens)',
      cloudVsLocalHeading: 'Cloud API vs Local GPU Mode',
      localOption: 'Local GPU Hosting (LM Studio / Ollama)',
      cloudOption: 'Cloud API Provider (DeepSeek / OpenAI / Claude)',
      promptCachingNotice: 'Prompt Caching enabled (saves ~50% on input tokens)',
      applySettings: 'Apply Settings to Config',
      disclaimer: '* Note: These figures are estimates based on standard literary averages (~275 words/page).',
    },

    // Settings Refactored View
    settings: {
      title: 'GPU & LLM Engine Configuration',
      subtitle: 'Manage your API providers, models, translation parameters, and application preferences.',

      // Internal Sidebar Tabs
      tabProviders: 'Providers & Models',
      tabTranslation: 'Translation Engine',
      tabGlobal: 'Global & Language',
      tabPresets: 'Config Presets',

      // Providers Tab
      chooseProvider: 'Choose LLM Provider',
      apiKey: 'Provider API Key',
      apiKeyPlaceholder: 'sk-...',
      notRequired: 'Not required for local hosting',
      activeModel: 'Active Model',
      detectingModels: 'Detecting models...',
      searchModelPlaceholder: 'Filter or search model...',
      customEndpoint: 'Endpoint URL',
      testConnection: 'Test Connection',
      testingConnection: 'Testing connection...',
      connectionSuccess: 'Connection successful!',
      connectionFailed: 'Connection failed',

      // Translation Engine Tab
      chunkSizeLabel: 'Segment Chunk Size ({count} tokens)',
      chunkSizeAdvice: 'Local GPU advice: 2500 | Cloud API: 8000',
      temperatureLabel: 'Temperature ({val})',
      temperatureAdvice: 'Recommended: 0.15 for precise literary translation',
      concurrencyLabel: 'Max Concurrency ({val} requests)',
      concurrencyAdvice: 'Local: 1-4 | Cloud API: 8-16',
      proofreadingTitle: 'Editorial Proofreading Pass (Pass 2)',
      proofreadingBadge: 'Pro Quality (99%)',
      proofreadingDesc: 'Runs a second editing pass on each segment to eliminate anglicisms and refine French literary style.',
      systemPromptTitle: 'System Prompt Presets',
      systemPromptDesc: 'Customize the instructions sent to the LLM for translation.',
      customPresetName: 'New preset name...',
      createPresetBtn: 'Create Preset',

      // Global Tab
      languageTitle: 'Application Interface Language',
      languageDesc: 'Choose the display language for the TraDoc interface.',
      langEnglish: 'English (Default)',
      langFrench: 'Français (French)',

      // Presets Manager Tab
      presetsManagerTitle: 'Configuration Profiles & Presets',
      presetsManagerDesc: 'Save complete snapshots of your provider, model, API keys, and translation settings.',
      saveCurrentAsPreset: 'Save Current Config as New Preset',
      presetNamePlaceholder: 'Preset Name (e.g. DeepSeek Cloud Fast)',
      savePresetBtn: 'Save Profile Preset',
      savedPresetsList: 'Saved Config Presets',
      activatePresetBtn: 'Activate',
      activeBadge: 'ACTIVE',
      deletePresetBtn: 'Delete Preset',
      confirmDeletePreset: 'Delete preset profile "{name}"?',
      
      saveAllSettings: 'Save All Settings',
      saveAllSuccess: 'Configuration saved successfully!',
    }
  },

  fr: {
    // Sidebar & Navigation Commune
    nav: {
      appName: 'TraDoc',
      appSubtitle: 'Traduction Littéraire IA',
      projects: 'Dashboard',
      inspector: 'Inspecteur & Suivi',
      vram: 'Estimateur',
      sandbox: 'Test',
      glossaries: 'Glossaire',
      settings: 'Paramètres',
      presets: 'Profils Presets',
      presetSelect: 'Sélectionner un Preset',
      defaultPreset: 'Preset par défaut',
      serverStatus: 'Serveur LLM',
      gpuOnline: 'GPU En ligne',
      gpuOffline: 'GPU Hors-ligne',
      unreachableBanner: 'Serveur GPU injoignable :',
      checkServerUrl: 'Vérifiez le serveur sur',
      configureIp: 'Configurer IP',
    },

    // Dashboard / Vue d'importation
    dashboard: {
      importBook: 'Importer un livre',
      dragDropText: 'Déposez votre livre ici ou cliquez pour choisir',
      supportedFormats: 'Fichier EPUB ou PDF littéraire',
      formatBadge: 'EPUB / PDF',
      translationMode: 'Mode Traduction EN → FR',
      proofreadMode: 'Mode Relecture & Correction Éditoriale',
      proofreadSourcePrompt: 'Sélectionnez un projet existant ou chargez le fichier pour la passe d\'édition :',
      sourceProject: 'Projet Source pour la Passe Éditoriale',
      uploadNewFile: 'Charger un Nouveau Fichier',
      llmModel: 'Modèle LLM',
      literaryGlossary: 'Glossaire Littéraire',
      noGlossary: 'Aucun glossaire',
      startTranslation: 'Démarrer la Traduction',
      startProofreading: 'Démarrer la Relecture Éditoriale',
      prepareInspect: 'Préparer & Inspecter (Sans lancer)',
      recentProjects: 'Projets enregistrés',
      noProjectsYet: 'Aucun projet actif ou terminé.',
      paused: 'EN PAUSE',
      completed: 'TERMINÉ',
      processing: 'EN COURS',
      failed: 'ÉCHOUÉ',
      resume: 'Reprendre',
      pause: 'Pause',
      inspect: 'Inspecter',
      downloadEpub: 'EPUB',
      deleteProject: 'Supprimer le Projet',
      confirmDelete: 'Supprimer définitivement le projet "{title}" ?',

      // Bloc Paramètres du Serveur
      serverParams: 'Paramètres du Serveur',
      provider: 'Fournisseur',
      model: 'Modèle Actif',
      concurrency: 'Concurrence',
      semanticWindow: 'Fenêtre Sémantique',
      requestsUnit: 'requêtes',
      tokensUnit: 'tokens',
      editConfig: 'Modifier la configuration',

      // Module Testeur en Direct
      liveTester: 'Testeur en Direct',
      liveTesterDesc: 'Testez vos phrases et votre modèle en 2 secondes sans importer de livre.',
      openSandbox: 'Ouvrir le Bac à Sable',
    },

    // Inspecteur de Segments
    inspector: {
      title: 'Inspecteur de Segment',
      selectProjectPrompt: 'Sélectionnez un projet dans le panneau de gauche pour inspecter les segments en temps réel.',
      projectsList: 'Livres & Projets',
      modeTranslation: 'Traduction',
      modeProofread: 'Relecture',
      segment: 'Segment',
      originalText: 'Texte Original Anglais (Source)',
      targetText: 'Traduction Française (Passe 1)',
      proofreadText: 'Rendu Relecture Éditoriale (Passe 2)',
      liveSseLogs: 'Journal des Événements SSE en Direct',
      noLogsYet: 'En attente du flux de logs...',
      copyText: 'Copier',
      copied: 'Copié !',
      reorderNotice: 'Double-cliquez sur n\'importe quel segment pour modifier la traduction directement.',
    },

    // Gestionnaire de Glossaires
    glossary: {
      title: 'Glossaires Littéraires',
      desc: 'Maintenez une terminologie stricte, des noms propres et une cohérence d\'univers.',
      aiPromptTitle: '1. Assistant Prompt IA (ChatGPT / Claude)',
      aiPromptDesc: 'Générez un glossaire propre depuis votre livre avec un prompt IA prêt à l\'emploi.',
      copyPromptBtn: 'Copier le Prompt d\'Extraction IA',
      promptCopied: 'Prompt copié dans le presse-papier !',

      pasteImportTitle: '2. Coller / Importer un Glossaire',
      pasteImportDesc: 'Collez les lignes générées par l\'IA (format Original | Traduction | Note) ou chargez un fichier.',
      pastePlaceholder: 'Nom_Personnage | Translation_Française | Note ou directive...',
      insertInList: 'Insérer dans la liste ci-dessous',
      uploadFileBtn: 'Charger un Fichier Glossaire',

      manualGuideTitle: '3. Guide de Création Manuel',
      manualGuideDesc: 'Comment structurer votre propre glossaire littéraire.',
      manualStep1: 'Utilisez 1 ligne par terme avec l\'orthographe exacte.',
      manualStep2: 'Ajoutez des notes de contexte (genre, vouvoiement/tutoiement, titres).',

      termsList: 'Tableau des Termes du Glossaire',
      sourceTerm: 'Terme Source (EN)',
      targetTerm: 'Traduction Cible (FR)',
      noteDirective: 'Note / Directive Éditoriale',
      action: 'Action',
      addNewTerm: 'Ajouter un Terme',
      searchPlaceholder: 'Rechercher un terme...',
      noTermsFound: 'Aucun terme défini dans ce glossaire.',
      confirmDeleteTerm: 'Supprimer le terme "{term}" ?',
      saveGlossary: 'Enregistrer le Glossaire',
      savedSuccess: 'Glossaire enregistré avec succès !',
    },

    // Bac à Sable
    sandbox: {
      title: 'Bac à Sable & Aperçu en Direct',
      desc: 'Testez votre modèle LLM actif sur des extraits littéraires avant de lancer une traduction complète.',
      sourceInputLabel: 'Extrait Source (EN)',
      resultOutputLabel: 'Résultat du Modèle (FR)',
      sampleText: 'C\'est une vérité universellement reconnue qu\'un célibataire pourvu d\'une belle fortune doit avoir envie de se marier.',
      runInference: 'Lancer l\'Inférence de Test',
      runningInference: 'Traitement en cours...',
      resetExcerpt: 'Réinitialiser le Texte Exemple',
      copyResult: 'Copier la Traduction',
    },

    // Assistant de Coûts / VRAM
    wizard: {
      title: 'Estimateur de Coûts & VRAM',
      desc: 'Calculez la consommation de tokens, les besoins VRAM GPU et les coûts API.',
      pageCountLabel: 'Nombre de Pages du Livre',
      sliderLabel: 'Curseur du nombre de pages',
      pagesUnit: 'pages',
      wordsEstimate: 'Estimation du nombre de mots : ~{count} mots',
      estimatedSegments: 'Segments Estimés ({chunkSize} tokens)',
      cloudVsLocalHeading: 'Mode Cloud API vs GPU Local',
      localOption: 'Hébergement GPU Local (LM Studio / Ollama)',
      cloudOption: 'Fournisseur Cloud API (DeepSeek / OpenAI / Claude)',
      promptCachingNotice: 'Prompt Caching activé (~50% d\'économie sur les tokens d\'entrée)',
      applySettings: 'Appliquer aux Réglages',
      disclaimer: '* Note : Ces chiffres restent des estimations calculées sur des moyennes littéraires (~275 mots/page).',
    },

    // Paramètres Refondus
    settings: {
      title: 'Configuration GPU & Moteur LLM',
      subtitle: 'Gérez vos fournisseurs API, modèles, paramètres de traduction et préférences globales.',

      // Onglets Sidebar Interne
      tabProviders: 'Fournisseurs & Modèles',
      tabTranslation: 'Moteur de Traduction',
      tabGlobal: 'Paramètres Globaux',
      tabPresets: 'Gestionnaire de Presets',

      // Onglet Providers
      chooseProvider: 'Choisir le Fournisseur LLM',
      apiKey: 'Clé API Fournisseur',
      apiKeyPlaceholder: 'sk-...',
      notRequired: 'Non requis pour l\'hébergement local',
      activeModel: 'Modèle Actif',
      detectingModels: 'Détection des modèles...',
      searchModelPlaceholder: 'Filtrer ou rechercher un modèle...',
      customEndpoint: 'Endpoint URL',
      testConnection: 'Tester la Connexion',
      testingConnection: 'Test de connexion...',
      connectionSuccess: 'Connexion réussie !',
      connectionFailed: 'Échec de la connexion',

      // Onglet Moteur de Traduction
      chunkSizeLabel: 'Taille du segment ({count} tokens)',
      chunkSizeAdvice: 'Conseil local : 2500 | Cloud API : 8000',
      temperatureLabel: 'Température ({val})',
      temperatureAdvice: 'Recommandé : 0.15 pour une traduction littéraire précise',
      concurrencyLabel: 'Concurrence Max ({val} requêtes)',
      concurrencyAdvice: 'Local : 1-4 | Cloud API : 8-16',
      proofreadingTitle: 'Relecture & Correcteur Éditorial (Passe 2)',
      proofreadingBadge: 'Qualité Pro (99%)',
      proofreadingDesc: 'Repasse chaque segment traduit dans un 2nd prompt d\'édition pour éliminer les anglicismes et lisser le style en français littéraire.',
      systemPromptTitle: 'Presets de Prompt Système',
      systemPromptDesc: 'Personnalisez les instructions envoyées au LLM pour la traduction.',
      customPresetName: 'Nom du nouveau preset...',
      createPresetBtn: 'Créer le Preset',

      // Onglet Globaux
      languageTitle: 'Langue de l\'Interface de l\'Application',
      languageDesc: 'Choisissez la langue d\'affichage de l\'interface TraDoc.',
      langEnglish: 'English (Anglais par défaut)',
      langFrench: 'Français (French)',

      // Onglet Presets Manager
      presetsManagerTitle: 'Profils de Configuration & Presets',
      presetsManagerDesc: 'Enregistrez des instantanés complets de votre fournisseur, modèle, clés API et paramètres de traduction.',
      saveCurrentAsPreset: 'Enregistrer la Config Actuelle comme Nouveau Preset',
      presetNamePlaceholder: 'Nom du Preset (ex: DeepSeek Cloud Rapide)',
      savePresetBtn: 'Enregistrer le Profil Preset',
      savedPresetsList: 'Presets de Config Enregistrés',
      activatePresetBtn: 'Activer',
      activeBadge: 'ACTIF',
      deletePresetBtn: 'Delete Preset',
      confirmDeletePreset: 'Supprimer le profil preset "{name}" ?',
      
      saveAllSettings: 'Enregistrer la Configuration',
      saveAllSuccess: 'Configuration enregistrée avec succès !',
    }
  }
};

// Helper pour récupérer une chaîne traduite avec fallback propre
export function t(keyPath, lang = 'en', params = {}) {
  const dictionary = translations[lang] || translations.en;
  const fallbackDict = translations.en;

  const keys = keyPath.split('.');
  let result = dictionary;
  let fallbackResult = fallbackDict;

  for (const key of keys) {
    if (result && typeof result === 'object') {
      result = result[key];
    } else {
      result = undefined;
    }
    if (fallbackResult && typeof fallbackResult === 'object') {
      fallbackResult = fallbackResult[key];
    } else {
      fallbackResult = undefined;
    }
  }

  let text = result !== undefined ? result : (fallbackResult !== undefined ? fallbackResult : keyPath);

  if (typeof text === 'string') {
    Object.keys(params).forEach((paramKey) => {
      text = text.replace(new RegExp(`\\{${paramKey}\\}`, 'g'), params[paramKey]);
    });
  }

  return text;
}
